name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Update scripts
    runs-on: ubuntu-latest
    steps:
      - name: Deploying authenticator server code to production server via ansible
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: ansible-playbook -v rhomis-ansible/setup.yml -i rhomis-ansible/inventory.yml --limit auth.rhomis.cgiar.org --tags update_prod_authenticator
